language: node_js

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

node_js:
  - 0.10
  - 0.12
  - 4.0
  - io.js

before_install:
  - export CXX=g++-4.8; export CC=gcc-4.8;
